# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - mynameisdax.md

footer: 'follow me on <a href="https://mastodon.ml/web/accounts/86734/">mastodon</a>'

#style: light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
